name: bred
version: '${project.version}'
main: org.mimja156.bred.Bred
api-version: '1.20'
commands:
  state:
    description: Enable or Disable the Bred plugin!
    usage: /<command> [enable | disable]
    permission: ADMINISTRATOR